### ISSUE TITLE
Loop Value must agree with future

### ISSUE THREAD

**Issue by Ghost---Shadow** [aio-libs/async-lru#245]
There is a possibility that multiple threads can access the same value before it is resolved.

Is there a way to ignore this error and just run the function without throwing?

EDIT: I found a temporary fix

```python
def safe_alru_cache(f):
    @functools.wraps(f)
    def wrapped(*args, **kwargs):
        try:
            cached_f = alru_cache(f)
            return cached_f(*args, **kwargs)
        except Exception as e:
            print(e)
            return f(*args, **kwargs)
    return wrapped
```

**Comment by asvetlov** [comment]
async-lru is for asyncio program, not for multithreading.
Access to the same asyncio object from different threads is dangerous
