### ISSUE TITLE
Custom size function support

### ISSUE THREAD

**Issue by bschindler** [aio-libs/async-lru#300]
cachetools has the feature for a custom size function to support things like caching files in memory and making sure the amount of bytes cached is not too large (as opposed to the amount of files cached). 

Would it be possible to add support for this? Since size may actually depend on the result of the cached function, size should be evaluated once the coroutine finished

Would it be possible to add a feature like this?

**Comment by asvetlov** [comment]
Not sure.
If cachetools has the feature maybe you should use it instead?
