### ISSUE TITLE
asyncio.shield 'loop' parameter deprecated in python 3.10

### ISSUE THREAD

**Issue by doggyhaha** [aio-libs/async-lru#383]
Hi, in python 3.10 the asyncio.shield 'loop' parameter has been removed, so it will raise 'TypeError: shield() got an unexpected keyword argument 'loop'

  File "C:\Users\Userr\AppData\Roaming\Python\Python310\site-packages\async_lru.py", line 237, in wrapped
    return (yield from asyncio.shield(fut, loop=_loop))
TypeError: shield() got an unexpected keyword argument 'loop'

**Comment by JrooTJunior** [comment]
@asvetlov, do you have any plans to update this library?
Or maybe you can approve PR and make an release when someones make this?

**Comment by grafuls** [comment]
Getting the same issue when running via container for python:3-alpine.
Had to downgrade the container to utilize python:3.9-alpine instead.
Is there an ETA for a new version containing this fix?

**Comment by upeshphable** [comment]
> This is actually fixed in [95ce3f1](https://github.com/aio-libs/async-lru/commit/95ce3f15f6a4aadbee0aa7cb65bd1de6f82bb73b). However, it is not publicly released yet.

When is it going to be released?

**Comment by webknjaz** [comment]
https://pypi.org/project/async-lru/1.0.3/
