### ISSUE TITLE
create a new release

### ISSUE THREAD

**Issue by andrew-ld** [aio-libs/async-lru#414]
since the issue https://github.com/aio-libs/async-lru/issues/383 was resolved by the https://github.com/aio-libs/async-lru/commit/339b4503e4cb2e28e3d940544aca18fd0d5135a7 commit, it would be necessary to create a new release and publish it on pypi.

**Comment by Harmon758** [comment]
[v1.0.3](https://github.com/aio-libs/async-lru/releases/tag/v1.0.3) has been released and [published to PyPI](https://pypi.org/project/async-lru/1.0.3/) now.
