### ISSUE TITLE
Does alru_cache prevent concurrent writes?

### ISSUE THREAD

**Issue by egeromin** [aio-libs/async-lru#447]
Suppose we have an alru_cached function with side effects, for example, sending an email

```python
from collections import defaultdict
from async_lru import alru_cache

num_email_confirmations = defaultdict(int)

@alru_cache(maxsize=500)
async def send_email_confirmation(user_email: str) -> int:
    _send_confirmation(user_email)
    num_email_confirmations[user_email] += 1
    return num_email_confirmations[user_email] 
```

Now, what happens if we concurrently try to send the same user `albert.einstein@example.com` an email multiple times, while the callback hasn't completed yet? Example:

```python
send_once = asyncio.create_task(send_email_confirmation("albert.einstein@example.com"))
send_again = asyncio.create_task(send_email_confirmation("albert.einstein@example.com"))
await send_once
await send_again

assert send_again == 1
```

Now, [running a minimal test](https://gist.github.com/egeromin/6348ed27debf510215266e07e7c5309e) and [checking the code](https://github.com/aio-libs/async-lru/blob/master/async_lru.py#L145) confirms that Albert should only receive his email once, since we are populating the cache with a future immediately. Is this behaviour documented or not? If so, would be great to document it explicitly. We are currently relying on this behaviour in our code.

**Comment by asvetlov** [comment]
Yes, it is intentional behavior.
Please feel free to provide a merge request with a documentation update.

**Comment by Dreamsorcerer** [comment]
Seems to be several tests that verify this behaviour, so I've just added an extra sentence to the README.
