### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ahivert** [aio-libs/async-lru#495]
Could it be possible to publish a new release on pypi since this PR is merged ?
https://github.com/aio-libs/async-lru/pull/481

**Comment by Dreamsorcerer** [comment]
@webknjaz Do you have any idea what's happening? The deploy pipeline succeeds, but there's no release on PyPI...

**Comment by webknjaz** [comment]
Yes: https://github.com/aio-libs/async-lru/commit/37a63eeffee8cba8219b4ecde1f4865b785e9f7f#r120964491.

**Comment by webknjaz** [comment]
This is when the PyPI API token stopped being passed: https://github.com/aio-libs/async-lru/commit/00a0fb060b0d252b631fb2e185e17d70295164c2#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL124.
It'll work again once you complete the configuration of the CI workflow to actually make use of secretless publishing.

**Comment by webknjaz** [comment]
@Dreamsorcerer you can re-try triggering publishing now.

**Comment by webknjaz** [comment]
@Dreamsorcerer I made the configuration and dropped the secrets on GitHub, you still need to revoke that API token in your PyPI account. I'll leave the release to you now.

P.S. There's a possibility that the `permissions` are now too restrictive. If the GH release update step fails, you'll probably need to add `contents: write` and restart.

**Comment by Dreamsorcerer** [comment]
OK, sorted. Thanks.

**Comment by webknjaz** [comment]
Release: https://pypi.org/project/async-lru/2.0.3/.

**Comment by webknjaz** [comment]
> OK, sorted. Thanks.

Did you revoke the PyPI API token on your side?

**Comment by Dreamsorcerer** [comment]
Yeah, trying. PyPI seems bugged and won't delete right now.

**Comment by webknjaz** [comment]
Well, if you didn't store it elsewhere, it's safe to postpone and try later, I suppose.
