### ISSUE TITLE
Correct the import source of `OrderedDict`

### ISSUE THREAD

**Issue by WH-2099** [aio-libs/async-lru#499]
`OrderedDict` should be imported from `collections` rather than `typing`.
The `OrderedDict` in `typing` is only used for type annotations and has been marked as deprecated since version 3.9.

https://docs.python.org/3/library/typing.html#typing.OrderedDict

https://docs.python.org/3/library/collections.html#ordereddict-objects

**Comment by Dreamsorcerer** [comment]
It's not only for type annotations, it's more of an alias with typing support.

We still support Python 3.8. We'll update all these imports (likely automatically with pyupgrade or similar) once we drop Python 3.8.
