### ISSUE TITLE
Error when the cache is cleared before the done callback is called

### ISSUE THREAD

**Issue by muraj238** [aio-libs/async-lru#503]
I'm sometimes getting a KeyError on self.__tasks.remove(task) on line 165 in the __init__.py. I think it's because the cache_clear() method is called before the task finishes, which clears the __tasks set and then the task can no longer be found there.  The code in the _task_done_callback method should be probably wrapped in the try/except block, or something like that.

**Comment by Dreamsorcerer** [comment]
Yes, I think we need a `if task in self.__tasks` check in `_task_done_callback()`. Probably also need to cancel the callbacks on `self.__cache` before clearing it as well.

Think you could create a test in a PR to reproduce the issue?

**Comment by muraj238** [comment]
> Yes, I think we need a `if task in self.__tasks` check in `_task_done_callback()`. Probably also need to cancel the callbacks on `self.__cache` before clearing it as well.
> 
> Think you could create a test in a PR to reproduce the issue?

#505 This is actually my first PR, so let me know if I created it properly, please.

**Comment by Dreamsorcerer** [comment]
I made a few changes to make it clearer what it is being tested and added a test for the cache items as well, and merged the fix. Thanks.
