### ISSUE TITLE
ttl doesnot work

### ISSUE THREAD

**Issue by yuanjie-ai** [aio-libs/async-lru#598]
```
@alru_cache(ttl=1)
async def get_token():
    await asyncio.sleep(3)


async def main():
    for i in range(10):
        with timer():
            await get_token()
        time.sleep(3)


if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by yuanjie-ai** [comment]
![image](https://github.com/user-attachments/assets/35f9444b-864c-468f-b264-f764de800de0)

**Comment by Dreamsorcerer** [comment]
TTL is implemented with an async callback, as your code doesn't yield to the event loop between calls, it has no opportunity to run. If you used `await asyncio.sleep(3)` instead I'd expect it to work.

**Comment by Dreamsorcerer** [comment]
As asyncio generally is not expected to work correctly when you block the event loop for >100ms or so, I don't think there's a bug here. I suggest enabled dev mode which should warn about these situations (e.g. `python -We -X dev ...`).
